# Generated by Django 5.2.11 on 2026-02-26 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
